# rename it to "config.yaml"

log_level: INFO


thornode:
  seed: https://chaosnet-seed.kylin.info/
  consensus:
    cohort: 3
    agree: 2

midgard:
  api_url: https://chaosnet-midgard.bepswap.com/


telegram:
  bot:
    token: "insert the bot token from @BotFather here"
  channels:
    - type: telegram
      name: "@kylin_alert"  # live channel
      lang: eng


tx:
  stake_unstake:
    min_pool_percent: 5
    max_age_sec: 12h
    fetch_period: 70
    tx_per_batch: 50
    max_page_deep: 10
    min_usd_total: 50000

price:
  fetch_period: 60
  global_cd: 12h
  change_cd: 1h
  percent_change_threshold: 5
  ath:
    cooldown: 2m
    stickers:
      - CAACAgIAAxkBAAIPuF-zvf5B1guBsIC8YqQE7jHnNP39AAJkBQACP5XMCgTLN7BUdOcAAR4E
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPvF-zvjn4-XPhcr-M06zZUUvwF700AAIpAAM7cR8iDQ6e_eGNDLUeBA
      - CAACAgIAAxkBAAIPvl-zvkRAYSkjyVNi9QxzovYSDK4DAAKqBQACP5XMCpXI5d6t1J7eHgQ
      - CAACAgIAAxkBAAIPwF-zvlRib5d5xSR1kWEwr0rpTJbIAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPol-zvRRRPSdC-Sr4lqhKsfNWWh3qAAJPAQACIjeOBHyVl0hMcbwXHgQ
      - CAACAgIAAxkBAAIPsF-zvVaSci3nhGf2-6l2YUEKcMKnAAICAAMUkqgdqsiIC2ZyV0oeBA
      - CAACAgIAAxkBAAIPsl-zvWI-Ihnnh0BSm6BM6DpYjYuJAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPuF-zvf5B1guBsIC8YqQE7jHnNP39AAJkBQACP5XMCgTLN7BUdOcAAR4E
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPvl-zvkRAYSkjyVNi9QxzovYSDK4DAAKqBQACP5XMCpXI5d6t1J7eHgQ
      - CAACAgIAAxkBAAIPwF-zvlRib5d5xSR1kWEwr0rpTJbIAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPwl-zyp2DJdPINcX6h0ZGesaakaMnAAJ9AwACbbBCA70TLvm2TbpTHgQ
      - CAACAgIAAxkBAAIPyV-zzEtVsFiaAWTVrJ8ROptFYUqjAAJFAAP3F4ErgJFXK7AarK4eBA
      - CAACAgIAAxkBAAJQsV_4emucc8THq6MbytL5PcclEG4NAAKMCwACLw_wBoRsyFANo_xWHgQ
      - CAACAgIAAxkBAAJQs1_4epK5KoxnhAJ3R5akKXpIfN1nAAKfAQACFkJrCmWMf9oXSSAlHgQ
      - CAACAgUAAxkBAAJQtV_4eqqciwvp9NCRdslyOoCKsOSaAAIdAAPRi-Yk3GCYqQrnOzceBA
      - CAACAgIAAxkBAAJQt1_4esnnDoR3NjLpgKHilirOZWybAAJsAAMUkqgduXN64vXUPDceBA
      - CAACAgUAAxkBAAJQuV_4eupYryWgJXeuLUu8xQsrfiBEAAIMAAPRi-Ykfll73qqZa3keBA
      - CAACAgUAAxkBAAJQu1_4eu8AAVG_deJgnwdKZcU9bsMYdgACGQAD0YvmJI2929l8C8ycHgQ
      - CAACAgUAAxkBAAJQvV_4ev8v5xXq_gABGb1O3g7UzdcZeAACHAAD0YvmJMnrKQclfN7VHgQ
      - CAACAgUAAxkBAAJQv1_4ewpDR4CoS3lWCVv2P0jEgZjfAAIUAAPRi-YkVzAp86uZwLMeBA
      - CAACAgUAAxkBAAJQw1_4ex7Ly2p8QAuLQvkeASXbgk9mAAIfAAPRi-YkQByn2GfGsIAeBA
      - CAACAgIAAxkBAAJQxV_4ezGuN6vz35bTfmLe4GPoT6GFAAKlAQACFkJrCqSMglNGCdzWHgQ

cap:
  fetch_period: 120


queue:
  fetch_period: 60
  threshold:
    avg_period: 10m
    congested: 20
    free: 2
  cooldown: 3600
